// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6bYSiCVgQaVvjI5ITFzttkZvkrnU_5_E',
    appId: '1:278496793189:web:95f7604689201456a66c8c',
    messagingSenderId: '278496793189',
    projectId: 'ludoboard-186a0',
    authDomain: 'ludoboard-186a0.firebaseapp.com',
    storageBucket: 'ludoboard-186a0.firebasestorage.app',
    measurementId: 'G-LX8GHL10W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7i8J7EgkP4iZLltFDBDCLKgAbelqPtcY',
    appId: '1:278496793189:android:33d04202f529d398a66c8c',
    messagingSenderId: '278496793189',
    projectId: 'ludoboard-186a0',
    storageBucket: 'ludoboard-186a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD4eoJpzmOU5LV1QTvko5GB075ODy3wmI',
    appId: '1:278496793189:ios:431b4898a17ee80ba66c8c',
    messagingSenderId: '278496793189',
    projectId: 'ludoboard-186a0',
    storageBucket: 'ludoboard-186a0.firebasestorage.app',
    iosBundleId: 'com.techskyway.ludo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD4eoJpzmOU5LV1QTvko5GB075ODy3wmI',
    appId: '1:278496793189:ios:abc65748e818303aa66c8c',
    messagingSenderId: '278496793189',
    projectId: 'ludoboard-186a0',
    storageBucket: 'ludoboard-186a0.firebasestorage.app',
    iosBundleId: 'com.example.ludogame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6bYSiCVgQaVvjI5ITFzttkZvkrnU_5_E',
    appId: '1:278496793189:web:5e84d1424d5239f7a66c8c',
    messagingSenderId: '278496793189',
    projectId: 'ludoboard-186a0',
    authDomain: 'ludoboard-186a0.firebaseapp.com',
    storageBucket: 'ludoboard-186a0.firebasestorage.app',
    measurementId: 'G-5N030L72LX',
  );
}
